<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsRole', 'doctrine');

/**
 * BaseCmsRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $user_id
 * @property string $user_name
 * @property timestamp $create_date
 * @property timestamp $modified_date
 * @property string $role_name
 * @property string $description
 * @property integer $status
 * @property integer $immune
 * @property integer $shareable
 * 
 * @method integer   getRoleId()        Returns the current record's "role_id" value
 * @method integer   getUserId()        Returns the current record's "user_id" value
 * @method string    getUserName()      Returns the current record's "user_name" value
 * @method timestamp getCreateDate()    Returns the current record's "create_date" value
 * @method timestamp getModifiedDate()  Returns the current record's "modified_date" value
 * @method string    getRoleName()      Returns the current record's "role_name" value
 * @method string    getDescription()   Returns the current record's "description" value
 * @method integer   getStatus()        Returns the current record's "status" value
 * @method integer   getImmune()        Returns the current record's "immune" value
 * @method integer   getShareable()     Returns the current record's "shareable" value
 * @method CmsRole   setRoleId()        Sets the current record's "role_id" value
 * @method CmsRole   setUserId()        Sets the current record's "user_id" value
 * @method CmsRole   setUserName()      Sets the current record's "user_name" value
 * @method CmsRole   setCreateDate()    Sets the current record's "create_date" value
 * @method CmsRole   setModifiedDate()  Sets the current record's "modified_date" value
 * @method CmsRole   setRoleName()      Sets the current record's "role_name" value
 * @method CmsRole   setDescription()   Sets the current record's "description" value
 * @method CmsRole   setStatus()        Sets the current record's "status" value
 * @method CmsRole   setImmune()        Sets the current record's "immune" value
 * @method CmsRole   setShareable()     Sets the current record's "shareable" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_role');
        $this->hasColumn('role_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_name', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('create_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('modified_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('role_name', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('immune', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('shareable', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}