<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SystemProperties', 'doctrine');

/**
 * BaseSystemProperties
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $key_
 * @property string $value_
 * @property string $description
 * @property timestamp $modifiedtime
 * @property timestamp $createdtime
 * @property integer $status
 * 
 * @method string           getKey_()         Returns the current record's "key_" value
 * @method string           getValue_()       Returns the current record's "value_" value
 * @method string           getDescription()  Returns the current record's "description" value
 * @method timestamp        getModifiedtime() Returns the current record's "modifiedtime" value
 * @method timestamp        getCreatedtime()  Returns the current record's "createdtime" value
 * @method integer          getStatus()       Returns the current record's "status" value
 * @method SystemProperties setKey_()         Sets the current record's "key_" value
 * @method SystemProperties setValue_()       Sets the current record's "value_" value
 * @method SystemProperties setDescription()  Sets the current record's "description" value
 * @method SystemProperties setModifiedtime() Sets the current record's "modifiedtime" value
 * @method SystemProperties setCreatedtime()  Sets the current record's "createdtime" value
 * @method SystemProperties setStatus()       Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSystemProperties extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('system_properties');
        $this->hasColumn('key_', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('value_', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('modifiedtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}