<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cpkey', 'doctrine');

/**
 * BaseCpkey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cpkeyid
 * @property string $cpid
 * @property string $keyconnect
 * 
 * @method integer getCpkeyid()    Returns the current record's "cpkeyid" value
 * @method string  getCpid()       Returns the current record's "cpid" value
 * @method string  getKeyconnect() Returns the current record's "keyconnect" value
 * @method Cpkey   setCpkeyid()    Sets the current record's "cpkeyid" value
 * @method Cpkey   setCpid()       Sets the current record's "cpid" value
 * @method Cpkey   setKeyconnect() Sets the current record's "keyconnect" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpkey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cpkey');
        $this->hasColumn('cpkeyid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cpid', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('keyconnect', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}