<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsGroupRight', 'doctrine');

/**
 * BaseCmsGroupRight
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $right_id
 * 
 * @method integer       getGroupId()  Returns the current record's "group_id" value
 * @method integer       getRightId()  Returns the current record's "right_id" value
 * @method CmsGroupRight setGroupId()  Sets the current record's "group_id" value
 * @method CmsGroupRight setRightId()  Sets the current record's "right_id" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsGroupRight extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_group_right');
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('right_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}