<?php

/**
 * BaseClientType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $clientId
 * @property bigint $code
 * @property string $name
 * @property Doctrine_Collection $Users
 * 
 * @method integer             getClientId() Returns the current record's "clientId" value
 * @method bigint              getCode()     Returns the current record's "code" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getUsers()    Returns the current record's "Users" collection
 * @method ClientType          setClientId() Sets the current record's "clientId" value
 * @method ClientType          setCode()     Sets the current record's "code" value
 * @method ClientType          setName()     Sets the current record's "name" value
 * @method ClientType          setUsers()    Sets the current record's "Users" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_type');
        $this->hasColumn('clientId', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'bigint', 11, array(
             'type' => 'bigint',
             'comment' => 'mã hệ điều hành',
             'length' => 11,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tên',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserInfo as Users', array(
             'local' => 'ClientId',
             'foreign' => 'clientId'));
    }
}