<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Announcement', 'doctrine');

/**
 * BaseAnnouncement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $announcementid
 * @property string $cp
 * @property string $subject
 * @property string $content
 * @property timestamp $createdtime
 * 
 * @method integer      getAnnouncementid() Returns the current record's "announcementid" value
 * @method string       getCp()             Returns the current record's "cp" value
 * @method string       getSubject()        Returns the current record's "subject" value
 * @method string       getContent()        Returns the current record's "content" value
 * @method timestamp    getCreatedtime()    Returns the current record's "createdtime" value
 * @method Announcement setAnnouncementid() Sets the current record's "announcementid" value
 * @method Announcement setCp()             Sets the current record's "cp" value
 * @method Announcement setSubject()        Sets the current record's "subject" value
 * @method Announcement setContent()        Sets the current record's "content" value
 * @method Announcement setCreatedtime()    Sets the current record's "createdtime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnouncement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('announcement');
        $this->hasColumn('announcementid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cp', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('subject', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('content', 'string', 5000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5000,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}