<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Option', 'doctrine');

/**
 * BaseOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $optionid
 * @property string $name
 * @property string $description
 * @property string $value
 * 
 * @method integer getOptionid()    Returns the current record's "optionid" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getValue()       Returns the current record's "value" value
 * @method Option  setOptionid()    Sets the current record's "optionid" value
 * @method Option  setName()        Sets the current record's "name" value
 * @method Option  setDescription() Sets the current record's "description" value
 * @method Option  setValue()       Sets the current record's "value" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('option');
        $this->hasColumn('optionid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4000,
             ));
        $this->hasColumn('value', 'string', 4000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}