<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Medal', 'doctrine');

/**
 * BaseMedal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $medal
 * @property string $name
 * @property string $description
 * @property integer $maxlevel
 * @property blob $_bytes
 * @property Doctrine_Collection $UserInfo
 * 
 * @method integer             getMedal()       Returns the current record's "medal" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getMaxlevel()    Returns the current record's "maxlevel" value
 * @method blob                get_bytes()      Returns the current record's "_bytes" value
 * @method Doctrine_Collection getUserInfo()    Returns the current record's "UserInfo" collection
 * @method Medal               setMedal()       Sets the current record's "medal" value
 * @method Medal               setName()        Sets the current record's "name" value
 * @method Medal               setDescription() Sets the current record's "description" value
 * @method Medal               setMaxlevel()    Sets the current record's "maxlevel" value
 * @method Medal               set_bytes()      Sets the current record's "_bytes" value
 * @method Medal               setUserInfo()    Sets the current record's "UserInfo" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('medal');
        $this->hasColumn('medal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('maxlevel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('_bytes', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserInfo', array(
             'local' => 'medal',
             'foreign' => 'medal'));
    }
}