<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsGroup', 'doctrine');

/**
 * BaseCmsGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $user_id
 * @property string $user_name
 * @property timestamp $create_date
 * @property integer $category_id
 * @property timestamp $modified_date
 * @property string $group_name
 * @property integer $status
 * @property string $description
 * 
 * @method integer   getGroupId()       Returns the current record's "group_id" value
 * @method integer   getUserId()        Returns the current record's "user_id" value
 * @method string    getUserName()      Returns the current record's "user_name" value
 * @method timestamp getCreateDate()    Returns the current record's "create_date" value
 * @method integer   getCategoryId()    Returns the current record's "category_id" value
 * @method timestamp getModifiedDate()  Returns the current record's "modified_date" value
 * @method string    getGroupName()     Returns the current record's "group_name" value
 * @method integer   getStatus()        Returns the current record's "status" value
 * @method string    getDescription()   Returns the current record's "description" value
 * @method CmsGroup  setGroupId()       Sets the current record's "group_id" value
 * @method CmsGroup  setUserId()        Sets the current record's "user_id" value
 * @method CmsGroup  setUserName()      Sets the current record's "user_name" value
 * @method CmsGroup  setCreateDate()    Sets the current record's "create_date" value
 * @method CmsGroup  setCategoryId()    Sets the current record's "category_id" value
 * @method CmsGroup  setModifiedDate()  Sets the current record's "modified_date" value
 * @method CmsGroup  setGroupName()     Sets the current record's "group_name" value
 * @method CmsGroup  setStatus()        Sets the current record's "status" value
 * @method CmsGroup  setDescription()   Sets the current record's "description" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_group');
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_name', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('create_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('modified_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('group_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}