<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AppChanRule', 'doctrine');

/**
 * BaseAppChanRule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ruleid
 * @property string $name
 * @property string $description
 * @property integer $point
 * @property integer $dich
 * 
 * @method integer     getRuleid()      Returns the current record's "ruleid" value
 * @method string      getName()        Returns the current record's "name" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method integer     getPoint()       Returns the current record's "point" value
 * @method integer     getDich()        Returns the current record's "dich" value
 * @method AppChanRule setRuleid()      Sets the current record's "ruleid" value
 * @method AppChanRule setName()        Sets the current record's "name" value
 * @method AppChanRule setDescription() Sets the current record's "description" value
 * @method AppChanRule setPoint()       Sets the current record's "point" value
 * @method AppChanRule setDich()        Sets the current record's "dich" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppChanRule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('app_chan_rule');
        $this->hasColumn('ruleid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('description', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('point', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dich', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}