<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OpenId', 'doctrine');

/**
 * BaseOpenId
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userid
 * @property integer $channel
 * @property timestamp $createdtime
 * @property string $openid
 * @property string $displayname
 * 
 * @method integer   getUserid()      Returns the current record's "userid" value
 * @method integer   getChannel()     Returns the current record's "channel" value
 * @method timestamp getCreatedtime() Returns the current record's "createdtime" value
 * @method string    getOpenid()      Returns the current record's "openid" value
 * @method string    getDisplayname() Returns the current record's "displayname" value
 * @method OpenId    setUserid()      Sets the current record's "userid" value
 * @method OpenId    setChannel()     Sets the current record's "channel" value
 * @method OpenId    setCreatedtime() Sets the current record's "createdtime" value
 * @method OpenId    setOpenid()      Sets the current record's "openid" value
 * @method OpenId    setDisplayname() Sets the current record's "displayname" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpenId extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('open_id');
        $this->hasColumn('userid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('channel', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('openid', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('displayname', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}