<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsRight', 'doctrine');

/**
 * BaseCmsRight
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $right_id
 * @property integer $user_id
 * @property string $user_name
 * @property timestamp $create_date
 * @property timestamp $modified_date
 * @property integer $category_id
 * @property integer $right_type
 * @property string $description
 * @property string $right_name
 * @property integer $status
 * 
 * @method integer   getRightId()       Returns the current record's "right_id" value
 * @method integer   getUserId()        Returns the current record's "user_id" value
 * @method string    getUserName()      Returns the current record's "user_name" value
 * @method timestamp getCreateDate()    Returns the current record's "create_date" value
 * @method timestamp getModifiedDate()  Returns the current record's "modified_date" value
 * @method integer   getCategoryId()    Returns the current record's "category_id" value
 * @method integer   getRightType()     Returns the current record's "right_type" value
 * @method string    getDescription()   Returns the current record's "description" value
 * @method string    getRightName()     Returns the current record's "right_name" value
 * @method integer   getStatus()        Returns the current record's "status" value
 * @method CmsRight  setRightId()       Sets the current record's "right_id" value
 * @method CmsRight  setUserId()        Sets the current record's "user_id" value
 * @method CmsRight  setUserName()      Sets the current record's "user_name" value
 * @method CmsRight  setCreateDate()    Sets the current record's "create_date" value
 * @method CmsRight  setModifiedDate()  Sets the current record's "modified_date" value
 * @method CmsRight  setCategoryId()    Sets the current record's "category_id" value
 * @method CmsRight  setRightType()     Sets the current record's "right_type" value
 * @method CmsRight  setDescription()   Sets the current record's "description" value
 * @method CmsRight  setRightName()     Sets the current record's "right_name" value
 * @method CmsRight  setStatus()        Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsRight extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_right');
        $this->hasColumn('right_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_name', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('create_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('modified_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('right_type', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('right_name', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}