<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Partner', 'doctrine');

/**
 * BasePartner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $partnerid
 * @property string $partnername
 * @property string $smsnumber
 * @property string $username
 * @property string $password
 * @property string $accesskey1
 * @property string $accesskey2
 * @property timestamp $createdtime
 * @property Doctrine_Collection $Users
 * 
 * @method integer             getPartnerid()   Returns the current record's "partnerid" value
 * @method string              getPartnername() Returns the current record's "partnername" value
 * @method string              getSmsnumber()   Returns the current record's "smsnumber" value
 * @method string              getUsername()    Returns the current record's "username" value
 * @method string              getPassword()    Returns the current record's "password" value
 * @method string              getAccesskey1()  Returns the current record's "accesskey1" value
 * @method string              getAccesskey2()  Returns the current record's "accesskey2" value
 * @method timestamp           getCreatedtime() Returns the current record's "createdtime" value
 * @method Doctrine_Collection getUsers()       Returns the current record's "Users" collection
 * @method Partner             setPartnerid()   Sets the current record's "partnerid" value
 * @method Partner             setPartnername() Sets the current record's "partnername" value
 * @method Partner             setSmsnumber()   Sets the current record's "smsnumber" value
 * @method Partner             setUsername()    Sets the current record's "username" value
 * @method Partner             setPassword()    Sets the current record's "password" value
 * @method Partner             setAccesskey1()  Sets the current record's "accesskey1" value
 * @method Partner             setAccesskey2()  Sets the current record's "accesskey2" value
 * @method Partner             setCreatedtime() Sets the current record's "createdtime" value
 * @method Partner             setUsers()       Sets the current record's "Users" collection
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partner');
        $this->hasColumn('partnerid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('partnername', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('smsnumber', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('accesskey1', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('accesskey2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserInfo as Users', array(
             'local' => 'partnerId',
             'foreign' => 'cp'));
    }
}