<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Friend', 'doctrine');

/**
 * BaseFriend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $friendid
 * @property integer $leftuserid
 * @property integer $rightuserid
 * @property timestamp $createdtime
 * @property timestamp $acceptedtime
 * @property integer $status
 * 
 * @method integer   getFriendid()     Returns the current record's "friendid" value
 * @method integer   getLeftuserid()   Returns the current record's "leftuserid" value
 * @method integer   getRightuserid()  Returns the current record's "rightuserid" value
 * @method timestamp getCreatedtime()  Returns the current record's "createdtime" value
 * @method timestamp getAcceptedtime() Returns the current record's "acceptedtime" value
 * @method integer   getStatus()       Returns the current record's "status" value
 * @method Friend    setFriendid()     Sets the current record's "friendid" value
 * @method Friend    setLeftuserid()   Sets the current record's "leftuserid" value
 * @method Friend    setRightuserid()  Sets the current record's "rightuserid" value
 * @method Friend    setCreatedtime()  Sets the current record's "createdtime" value
 * @method Friend    setAcceptedtime() Sets the current record's "acceptedtime" value
 * @method Friend    setStatus()       Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friend');
        $this->hasColumn('friendid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('leftuserid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('rightuserid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('acceptedtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}