<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DownloadCount', 'doctrine');

/**
 * BaseDownloadCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $downloadcountid
 * @property string $ip
 * @property string $platform
 * @property timestamp $downloadedtime
 * @property string $cp
 * @property string $type
 * 
 * @method integer       getDownloadcountid() Returns the current record's "downloadcountid" value
 * @method string        getIp()              Returns the current record's "ip" value
 * @method string        getPlatform()        Returns the current record's "platform" value
 * @method timestamp     getDownloadedtime()  Returns the current record's "downloadedtime" value
 * @method string        getCp()              Returns the current record's "cp" value
 * @method string        getType()            Returns the current record's "type" value
 * @method DownloadCount setDownloadcountid() Sets the current record's "downloadcountid" value
 * @method DownloadCount setIp()              Sets the current record's "ip" value
 * @method DownloadCount setPlatform()        Sets the current record's "platform" value
 * @method DownloadCount setDownloadedtime()  Sets the current record's "downloadedtime" value
 * @method DownloadCount setCp()              Sets the current record's "cp" value
 * @method DownloadCount setType()            Sets the current record's "type" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDownloadCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('download_count');
        $this->hasColumn('downloadcountid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ip', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('platform', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('downloadedtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}