<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GameProvider', 'doctrine');

/**
 * BaseGameProvider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $providerid
 * @property string $providername
 * @property string $md5key
 * @property string $defaultcp
 * 
 * @method integer      getProviderid()   Returns the current record's "providerid" value
 * @method string       getProvidername() Returns the current record's "providername" value
 * @method string       getMd5key()       Returns the current record's "md5key" value
 * @method string       getDefaultcp()    Returns the current record's "defaultcp" value
 * @method GameProvider setProviderid()   Sets the current record's "providerid" value
 * @method GameProvider setProvidername() Sets the current record's "providername" value
 * @method GameProvider setMd5key()       Sets the current record's "md5key" value
 * @method GameProvider setDefaultcp()    Sets the current record's "defaultcp" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGameProvider extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game_provider');
        $this->hasColumn('providerid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('providername', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('md5key', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('defaultcp', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}