<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OnlineLog', 'doctrine');

/**
 * BaseOnlineLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $logid
 * @property string $peakdata
 * @property timestamp $insertedtime
 * 
 * @method integer   getLogid()        Returns the current record's "logid" value
 * @method string    getPeakdata()     Returns the current record's "peakdata" value
 * @method timestamp getInsertedtime() Returns the current record's "insertedtime" value
 * @method OnlineLog setLogid()        Sets the current record's "logid" value
 * @method OnlineLog setPeakdata()     Sets the current record's "peakdata" value
 * @method OnlineLog setInsertedtime() Sets the current record's "insertedtime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOnlineLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('online_log');
        $this->hasColumn('logid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('peakdata', 'string', 2000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2000,
             ));
        $this->hasColumn('insertedtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}