<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SmsLog', 'doctrine');

/**
 * BaseSmsLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $smslogid
 * @property string $sender
 * @property string $recipient
 * @property string $mobody
 * @property string $mtbody
 * @property string $cp
 * @property integer $status
 * @property timestamp $createdtime
 * @property string $sendnumber
 * 
 * @method integer   getSmslogid()    Returns the current record's "smslogid" value
 * @method string    getSender()      Returns the current record's "sender" value
 * @method string    getRecipient()   Returns the current record's "recipient" value
 * @method string    getMobody()      Returns the current record's "mobody" value
 * @method string    getMtbody()      Returns the current record's "mtbody" value
 * @method string    getCp()          Returns the current record's "cp" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getCreatedtime() Returns the current record's "createdtime" value
 * @method string    getSendnumber()  Returns the current record's "sendnumber" value
 * @method SmsLog    setSmslogid()    Sets the current record's "smslogid" value
 * @method SmsLog    setSender()      Sets the current record's "sender" value
 * @method SmsLog    setRecipient()   Sets the current record's "recipient" value
 * @method SmsLog    setMobody()      Sets the current record's "mobody" value
 * @method SmsLog    setMtbody()      Sets the current record's "mtbody" value
 * @method SmsLog    setCp()          Sets the current record's "cp" value
 * @method SmsLog    setStatus()      Sets the current record's "status" value
 * @method SmsLog    setCreatedtime() Sets the current record's "createdtime" value
 * @method SmsLog    setSendnumber()  Sets the current record's "sendnumber" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_log');
        $this->hasColumn('smslogid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('sender', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('recipient', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('mobody', 'string', 160, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 160,
             ));
        $this->hasColumn('mtbody', 'string', 160, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 160,
             ));
        $this->hasColumn('cp', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sendnumber', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}