<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BetGold', 'doctrine');

/**
 * BaseBetGold
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $betgoldid
 * @property integer $gold
 * 
 * @method integer getBetgoldid() Returns the current record's "betgoldid" value
 * @method integer getGold()      Returns the current record's "gold" value
 * @method BetGold setBetgoldid() Sets the current record's "betgoldid" value
 * @method BetGold setGold()      Sets the current record's "gold" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBetGold extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bet_gold');
        $this->hasColumn('betgoldid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('gold', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}