<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AvatarBuy', 'doctrine');

/**
 * BaseAvatarBuy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $avatarbuyid
 * @property integer $userid
 * @property string $username
 * @property integer $avatarid
 * @property timestamp $boughttime
 * 
 * @method integer   getAvatarbuyid() Returns the current record's "avatarbuyid" value
 * @method integer   getUserid()      Returns the current record's "userid" value
 * @method string    getUsername()    Returns the current record's "username" value
 * @method integer   getAvatarid()    Returns the current record's "avatarid" value
 * @method timestamp getBoughttime()  Returns the current record's "boughttime" value
 * @method AvatarBuy setAvatarbuyid() Sets the current record's "avatarbuyid" value
 * @method AvatarBuy setUserid()      Sets the current record's "userid" value
 * @method AvatarBuy setUsername()    Sets the current record's "username" value
 * @method AvatarBuy setAvatarid()    Sets the current record's "avatarid" value
 * @method AvatarBuy setBoughttime()  Sets the current record's "boughttime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvatarBuy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('avatar_buy');
        $this->hasColumn('avatarbuyid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('username', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('avatarid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('boughttime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}