<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsUserRole', 'doctrine');

/**
 * BaseCmsUserRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $role_id
 * 
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method integer     getRoleId()  Returns the current record's "role_id" value
 * @method CmsUserRole setUserId()  Sets the current record's "user_id" value
 * @method CmsUserRole setRoleId()  Sets the current record's "role_id" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsUserRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_user_role');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('role_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}