<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GvTestCase', 'doctrine');

/**
 * BaseGvTestCase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $test_key
 * @property string $value
 * @property integer $game_id
 * @property string $description
 * @property integer $status
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method string     getTestKey()     Returns the current record's "test_key" value
 * @method string     getValue()       Returns the current record's "value" value
 * @method integer    getGameId()      Returns the current record's "game_id" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method integer    getStatus()      Returns the current record's "status" value
 * @method GvTestCase setId()          Sets the current record's "id" value
 * @method GvTestCase setTestKey()     Sets the current record's "test_key" value
 * @method GvTestCase setValue()       Sets the current record's "value" value
 * @method GvTestCase setGameId()      Sets the current record's "game_id" value
 * @method GvTestCase setDescription() Sets the current record's "description" value
 * @method GvTestCase setStatus()      Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGvTestCase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gv_test_case');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('test_key', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('value', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 512,
             ));
        $this->hasColumn('game_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}