<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MatchLog', 'doctrine');

/**
 * BaseMatchLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $matchlogid
 * @property integer $roomid
 * @property integer $matchindex
 * @property integer $gameid
 * @property string $description
 * @property timestamp $createdtime
 * 
 * @method integer   getMatchlogid()  Returns the current record's "matchlogid" value
 * @method integer   getRoomid()      Returns the current record's "roomid" value
 * @method integer   getMatchindex()  Returns the current record's "matchindex" value
 * @method integer   getGameid()      Returns the current record's "gameid" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method timestamp getCreatedtime() Returns the current record's "createdtime" value
 * @method MatchLog  setMatchlogid()  Sets the current record's "matchlogid" value
 * @method MatchLog  setRoomid()      Sets the current record's "roomid" value
 * @method MatchLog  setMatchindex()  Sets the current record's "matchindex" value
 * @method MatchLog  setGameid()      Sets the current record's "gameid" value
 * @method MatchLog  setDescription() Sets the current record's "description" value
 * @method MatchLog  setCreatedtime() Sets the current record's "createdtime" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMatchLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('match_log');
        $this->hasColumn('matchlogid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('roomid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('matchindex', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('gameid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4000,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}