<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AvatarResource', 'doctrine');

/**
 * BaseAvatarResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $avatarresourceid
 * @property string $name
 * @property string $description
 * @property string $path
 * @property integer $cash
 * @property integer $gold
 * @property integer $buynumber
 * @property timestamp $createdtime
 * @property timestamp $modifiedtime
 * @property integer $width
 * @property integer $height
 * 
 * @method integer        getAvatarresourceid() Returns the current record's "avatarresourceid" value
 * @method string         getName()             Returns the current record's "name" value
 * @method string         getDescription()      Returns the current record's "description" value
 * @method string         getPath()             Returns the current record's "path" value
 * @method integer        getCash()             Returns the current record's "cash" value
 * @method integer        getGold()             Returns the current record's "gold" value
 * @method integer        getBuynumber()        Returns the current record's "buynumber" value
 * @method timestamp      getCreatedtime()      Returns the current record's "createdtime" value
 * @method timestamp      getModifiedtime()     Returns the current record's "modifiedtime" value
 * @method integer        getWidth()            Returns the current record's "width" value
 * @method integer        getHeight()           Returns the current record's "height" value
 * @method AvatarResource setAvatarresourceid() Sets the current record's "avatarresourceid" value
 * @method AvatarResource setName()             Sets the current record's "name" value
 * @method AvatarResource setDescription()      Sets the current record's "description" value
 * @method AvatarResource setPath()             Sets the current record's "path" value
 * @method AvatarResource setCash()             Sets the current record's "cash" value
 * @method AvatarResource setGold()             Sets the current record's "gold" value
 * @method AvatarResource setBuynumber()        Sets the current record's "buynumber" value
 * @method AvatarResource setCreatedtime()      Sets the current record's "createdtime" value
 * @method AvatarResource setModifiedtime()     Sets the current record's "modifiedtime" value
 * @method AvatarResource setWidth()            Sets the current record's "width" value
 * @method AvatarResource setHeight()           Sets the current record's "height" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvatarResource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('avatar_resource');
        $this->hasColumn('avatarresourceid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('description', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('path', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('cash', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('gold', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('buynumber', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('modifiedtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('width', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('height', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}