<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AnnouncementReaded', 'doctrine');

/**
 * BaseAnnouncementReaded
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $announcementreadedid
 * @property integer $userid
 * @property integer $announcementid
 * 
 * @method integer            getAnnouncementreadedid() Returns the current record's "announcementreadedid" value
 * @method integer            getUserid()               Returns the current record's "userid" value
 * @method integer            getAnnouncementid()       Returns the current record's "announcementid" value
 * @method AnnouncementReaded setAnnouncementreadedid() Sets the current record's "announcementreadedid" value
 * @method AnnouncementReaded setUserid()               Sets the current record's "userid" value
 * @method AnnouncementReaded setAnnouncementid()       Sets the current record's "announcementid" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnnouncementReaded extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('announcement_readed');
        $this->hasColumn('announcementreadedid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('announcementid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}