<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExperienceValue', 'doctrine');

/**
 * BaseExperienceValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $experiencevalueid
 * @property integer $increase
 * @property string $description
 * 
 * @method integer         getExperiencevalueid() Returns the current record's "experiencevalueid" value
 * @method integer         getIncrease()          Returns the current record's "increase" value
 * @method string          getDescription()       Returns the current record's "description" value
 * @method ExperienceValue setExperiencevalueid() Sets the current record's "experiencevalueid" value
 * @method ExperienceValue setIncrease()          Sets the current record's "increase" value
 * @method ExperienceValue setDescription()       Sets the current record's "description" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExperienceValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('experience_value');
        $this->hasColumn('experiencevalueid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('increase', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}