<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TopupLog', 'doctrine');

/**
 * BaseTopupLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $topupid
 * @property timestamp $timetopup
 * @property string $username
 * @property string $cardserial
 * @property string $cardpin
 * @property integer $value
 * @property string $providercard
 * @property integer $currentcash
 * @property integer $currentgold
 * @property integer $status
 * @property integer $userid
 * 
 * @method integer   getTopupid()      Returns the current record's "topupid" value
 * @method timestamp getTimetopup()    Returns the current record's "timetopup" value
 * @method string    getUsername()     Returns the current record's "username" value
 * @method string    getCardserial()   Returns the current record's "cardserial" value
 * @method string    getCardpin()      Returns the current record's "cardpin" value
 * @method integer   getValue()        Returns the current record's "value" value
 * @method string    getProvidercard() Returns the current record's "providercard" value
 * @method integer   getCurrentcash()  Returns the current record's "currentcash" value
 * @method integer   getCurrentgold()  Returns the current record's "currentgold" value
 * @method integer   getStatus()       Returns the current record's "status" value
 * @method integer   getUserid()       Returns the current record's "userid" value
 * @method TopupLog  setTopupid()      Sets the current record's "topupid" value
 * @method TopupLog  setTimetopup()    Sets the current record's "timetopup" value
 * @method TopupLog  setUsername()     Sets the current record's "username" value
 * @method TopupLog  setCardserial()   Sets the current record's "cardserial" value
 * @method TopupLog  setCardpin()      Sets the current record's "cardpin" value
 * @method TopupLog  setValue()        Sets the current record's "value" value
 * @method TopupLog  setProvidercard() Sets the current record's "providercard" value
 * @method TopupLog  setCurrentcash()  Sets the current record's "currentcash" value
 * @method TopupLog  setCurrentgold()  Sets the current record's "currentgold" value
 * @method TopupLog  setStatus()       Sets the current record's "status" value
 * @method TopupLog  setUserid()       Sets the current record's "userid" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTopupLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('topup_log');
        $this->hasColumn('topupid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('timetopup', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('username', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('cardserial', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('cardpin', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('value', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('providercard', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('currentcash', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('currentgold', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('userid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}