<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Notification', 'doctrine');

/**
 * BaseNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $notificationid
 * @property string $pushmessage
 * @property integer $pushnumber
 * @property timestamp $pushtime
 * @property string $cp
 * 
 * @method integer      getNotificationid() Returns the current record's "notificationid" value
 * @method string       getPushmessage()    Returns the current record's "pushmessage" value
 * @method integer      getPushnumber()     Returns the current record's "pushnumber" value
 * @method timestamp    getPushtime()       Returns the current record's "pushtime" value
 * @method string       getCp()             Returns the current record's "cp" value
 * @method Notification setNotificationid() Sets the current record's "notificationid" value
 * @method Notification setPushmessage()    Sets the current record's "pushmessage" value
 * @method Notification setPushnumber()     Sets the current record's "pushnumber" value
 * @method Notification setPushtime()       Sets the current record's "pushtime" value
 * @method Notification setCp()             Sets the current record's "cp" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification');
        $this->hasColumn('notificationid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pushmessage', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('pushnumber', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pushtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cp', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}