<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CardProvider', 'doctrine');

/**
 * BaseCardProvider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cardproviderid
 * @property integer $cardid
 * @property string $cardname
 * @property string $submenu
 * @property integer $len1
 * @property integer $len2
 * @property string $cardmsg
 * 
 * @method integer      getCardproviderid() Returns the current record's "cardproviderid" value
 * @method integer      getCardid()         Returns the current record's "cardid" value
 * @method string       getCardname()       Returns the current record's "cardname" value
 * @method string       getSubmenu()        Returns the current record's "submenu" value
 * @method integer      getLen1()           Returns the current record's "len1" value
 * @method integer      getLen2()           Returns the current record's "len2" value
 * @method string       getCardmsg()        Returns the current record's "cardmsg" value
 * @method CardProvider setCardproviderid() Sets the current record's "cardproviderid" value
 * @method CardProvider setCardid()         Sets the current record's "cardid" value
 * @method CardProvider setCardname()       Sets the current record's "cardname" value
 * @method CardProvider setSubmenu()        Sets the current record's "submenu" value
 * @method CardProvider setLen1()           Sets the current record's "len1" value
 * @method CardProvider setLen2()           Sets the current record's "len2" value
 * @method CardProvider setCardmsg()        Sets the current record's "cardmsg" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCardProvider extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('card_provider');
        $this->hasColumn('cardproviderid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cardid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cardname', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('submenu', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('len1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('len2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cardmsg', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}