<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Link', 'doctrine');

/**
 * BaseLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $linkid
 * @property string $url
 * @property string $name
 * @property integer $userid
 * @property string $description
 * @property integer $clicked
 * @property timestamp $createdtime
 * @property timestamp $updatedtime
 * @property integer $introuserid
 * @property integer $status
 * 
 * @method integer   getLinkid()      Returns the current record's "linkid" value
 * @method string    getUrl()         Returns the current record's "url" value
 * @method string    getName()        Returns the current record's "name" value
 * @method integer   getUserid()      Returns the current record's "userid" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method integer   getClicked()     Returns the current record's "clicked" value
 * @method timestamp getCreatedtime() Returns the current record's "createdtime" value
 * @method timestamp getUpdatedtime() Returns the current record's "updatedtime" value
 * @method integer   getIntrouserid() Returns the current record's "introuserid" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method Link      setLinkid()      Sets the current record's "linkid" value
 * @method Link      setUrl()         Sets the current record's "url" value
 * @method Link      setName()        Sets the current record's "name" value
 * @method Link      setUserid()      Sets the current record's "userid" value
 * @method Link      setDescription() Sets the current record's "description" value
 * @method Link      setClicked()     Sets the current record's "clicked" value
 * @method Link      setCreatedtime() Sets the current record's "createdtime" value
 * @method Link      setUpdatedtime() Sets the current record's "updatedtime" value
 * @method Link      setIntrouserid() Sets the current record's "introuserid" value
 * @method Link      setStatus()      Sets the current record's "status" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     diepth2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('link');
        $this->hasColumn('linkid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('userid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('clicked', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('createdtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updatedtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('introuserid', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}