<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CmsRoleGroup', 'doctrine');

/**
 * BaseCmsRoleGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $group_id
 * 
 * @method integer      getRoleId()   Returns the current record's "role_id" value
 * @method integer      getGroupId()  Returns the current record's "group_id" value
 * @method CmsRoleGroup setRoleId()   Sets the current record's "role_id" value
 * @method CmsRoleGroup setGroupId()  Sets the current record's "group_id" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCmsRoleGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cms_role_group');
        $this->hasColumn('role_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}