<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MessageType', 'doctrine');

/**
 * BaseMessageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $messagetypeid
 * @property string $name
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method integer     getMessagetypeid() Returns the current record's "messagetypeid" value
 * @method string      getName()          Returns the current record's "name" value
 * @method MessageType setId()            Sets the current record's "id" value
 * @method MessageType setMessagetypeid() Sets the current record's "messagetypeid" value
 * @method MessageType setName()          Sets the current record's "name" value
 * 
 * @package    Vt_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessageType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('messagetypeid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}