<?php

/**
 * AnnouncementReadedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnouncementReadedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnouncementReadedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnnouncementReaded');
    }
}