<?php

/**
 * AppChanRuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppChanRuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppChanRuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AppChanRule');
    }
}