<?php

/**
 * AvatarResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvatarResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvatarResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvatarResource');
    }
}