<?php

/**
 * AvatarBuyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvatarBuyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvatarBuyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvatarBuy');
    }
}