<?php

/**
 * BetGoldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BetGoldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BetGoldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BetGold');
    }
}