<?php

/**
 * CardProviderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CardProviderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CardProviderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CardProvider');
    }
}