<?php

/**
 * CmsCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsCategory');
    }
}