<?php

/**
 * CmsCategoryFooterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsCategoryFooterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsCategoryFooterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsCategoryFooter');
    }
}