<?php

/**
 * CmsGroupRightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsGroupRightTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsGroupRightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsGroupRight');
    }
}