<?php

/**
 * CmsNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsNews');
    }
}