<?php

/**
 * CmsRightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsRightTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsRightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsRight');
    }
}