<?php

/**
 * CmsRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsRole');
    }
}