<?php

/**
 * CmsRoleGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsRoleGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsRoleGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsRoleGroup');
    }
}