<?php

/**
 * CmsUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsUser');
    }
}