<?php

/**
 * CmsUserRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CmsUserRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CmsUserRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CmsUserRole');
    }
}