<?php

/**
 * CpkeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpkeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpkeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cpkey');
    }
}