<?php

/**
 * CpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cp');
    }
}