<?php

/**
 * DataLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DataLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DataLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DataLog');
    }
}