<?php

/**
 * DownloadLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DownloadLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DownloadLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DownloadLog');
    }
}