<?php

/**
 * DownloadCountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DownloadCountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DownloadCountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DownloadCount');
    }
}