<?php

/**
 * EpayLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EpayLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EpayLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EpayLog');
    }
}