<?php

/**
 * EventRegisterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventRegisterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventRegisterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventRegister');
    }
}