<?php

/**
 * ExperienceValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExperienceValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExperienceValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExperienceValue');
    }
}