<?php

/**
 * GameTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameTransaction');
    }
}