<?php

/**
 * GameProviderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameProviderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameProviderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameProvider');
    }
}