<?php

/**
 * GameVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameVersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameVersion');
    }
}