<?php

/**
 * GameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Game');
    }
    public static  function getListGame($gameId = null)
    {
        $sql =   GameTable::getInstance()->createQuery('a')
            ->select('a.gameid, a.name')
            ->where('status = 1');
        if($gameId){
            $sql->andWhere("a.gameid =?", $gameId);
        }
        return $sql->fetchArray();
    }
}