<?php

/**
 * GameHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameHistory');
    }
}