<?php

/**
 * GameClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameClient');
    }
}