<?php

/**
 * GameLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GameLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GameLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GameLog');
    }
}