<?php

/**
 * GiftTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GiftType');
    }
}