<?php

/**
 * GiftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GiftTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GiftTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gift');
    }
}