<?php

/**
 * GvTestCaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GvTestCaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GvTestCaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GvTestCase');
    }
}