<?php

/**
 * HistoryFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoryFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoryFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistoryFilter');
    }
}