<?php

/**
 * HistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('History');
    }
}