<?php

/**
 * LevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Level');
    }
}