<?php

/**
 * LogPaymentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogPayment');
    }
    public static function writeLogs($userId, $money, $type, $status, $message, $seria, $card_code, $request_time){
        $log_payment = new LogPayment();
        $log_payment->setUserid($userId);
        $log_payment->setMoney($money);
        $log_payment->setSeria($seria);
        $log_payment->setPinCard($card_code);
        $log_payment->setContent(self::getContent($seria, $card_code));
        $log_payment->setType($type);
        $log_payment->setStatus($status);
        $log_payment->setMessage($message);
        $log_payment->setRequestTime($request_time);
        $log_payment->save();
    }

    private static function getContent($seria, $card_code){
        $arr = array();
        $arr['os'] = 'Web';
        $arr['cardserial'] = $seria;
        $arr['pincard'] = $card_code;

        return json_encode($arr);
    }
    public static function countLockPayment($userId){
        return LogPaymentTable::getInstance()->createQuery()
            ->where('userid = ?', $userId)
            ->andwhere('status = ?', '4')
            ->andwhere('request_time >=?',date("Y-m-d H:i:s", time() - 3600))
            ->count();
    }
    public static function resetLockPayment($userId) {
        $q = self::getInstance()->createQuery()
            ->delete()
            ->where('status = ?', '4')
            ->andwhere('userid = ?', $userId);
        return $q->execute();
    }
}