<?php

/**
 * LogPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogPayment');
    }
}