<?php

/**
 * MatchLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatchLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatchLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MatchLog');
    }
}