<?php

/**
 * MedalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medal');
    }
}