<?php

/**
 * MessageTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MessageType');
    }
}