<?php

/**
 * MoneyTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MoneyTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MoneyTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MoneyTransaction');
    }
}