<?php

/**
 * MoneyLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MoneyLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MoneyLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MoneyLog');
    }
}