<?php

/**
 * OpenIdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenIdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpenIdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpenId');
    }
}