<?php

/**
 * PartnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partner');
    }
    public static function getListPartnerForSelectBox()
    {
        $i18n = sfContext::getInstance()->getI18N();
        $listType[""] = $i18n->__("Tất cả");
        $arrType = PartnerTable::getInstance()->createQuery('a')
            ->select('a.partnerid, a.partnername')->fetchArray();
        foreach($arrType as $valType){
            $listType[$valType['partnerid']] = $valType['partnername'];
        }
        return $listType;
    }
}