<?php

/**
 * PasswordUpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PasswordUpdateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PasswordUpdateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PasswordUpdate');
    }
}