<?php

/**
 * PromotionRuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromotionRuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromotionRuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PromotionRule');
    }
}