<?php

/**
 * PurchaseMoneyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseMoneyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PurchaseMoneyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseMoney');
    }
}