<?php

/**
 * SliderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SliderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slider');
    }
}