<?php

/**
 * SmsLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsLog');
    }
}