<?php

/**
 * SmsTextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsTextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsTextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SmsText');
    }
}