<?php

/**
 * SuggestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuggestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuggestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Suggestion');
    }
}