<?php

/**
 * SystemPropertiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SystemPropertiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SystemPropertiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SystemProperties');
    }
}