<?php

/**
 * TopupLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TopupLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TopupLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TopupLog');
    }
}