<?php

/**
 * TransactionCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransactionCardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransactionCardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TransactionCard');
    }
}