<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    public static function getRegisterInfo($created_at)
    {
        return UserTable::getInstance()->createQuery('a')
            ->select ('count(*), date(registedTime)')
            ->groupby("date(registedTime)")
            ->where("a.registedTime > ?", $created_at)
            ->fetchArray();
    }

}