<?php

/**
 * UserInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserInfo');
    }
    public static function getTotalUserByOs()
    {
        $query = UserInfoTable::getInstance()->createQuery('a')
            ->select("count(a.clientId) as sum_os, c.name as os_name, a.clientId ");
        $query ->groupBy("a.clientId");
        $query->leftJoin("a.ClientType c");
        $query->orderBy("sum_os desc");
        return $query->fetchArray();
    }
}