<?php

/**
 * VtUserSigninLockTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtUserSigninLockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtUserSigninLockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtUserSigninLock');
    }

    public static function resetUserSigninLock($user_name) {
        $q = self::getInstance()->createQuery()
            ->delete()
            ->where('user_name = ?', $user_name);

        return $q->execute();
    }

    public static function getCountUserSig($user_name, $time) {
        $q = self::getInstance()->createQuery()
            ->where('user_name = ?', $user_name)
            ->andwhere('created_time >=?', $time);

        return $q->count();
    }

    /**
     * Hàm tính số phút còn lại mà tài khoản bị khóa
     * @param $usn
     * @param $timeLock: số phút bị khóa, mặc định 30 phút
     * @return float|int
     */
    public static function timeMeaningPubSignin($usn, $timeLock = 30)
    {
        $usn = htmlentities(strip_tags($usn));
        $timeLock = (int)$timeLock;
        $pubLock = self::getInstance()->createQuery('a')
            ->where('user_name = ?', $usn)
            ->andwhere('created_time >= ?', strtotime(date('Y-m-d H:i:s', time() - 30*60)))
            ->fetchOne();
        if($pubLock){
            return round(($timeLock*60 - (strtotime(date('Y-m-d H:i:s')) - $pubLock['created_time']))/60);
        }else{
            return -1;
        }
    }
}