<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/05 05:00:23

return array(
'slave' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=103.28.37.24;dbname=gamevina_v2',
  'username' => 'root',
  'password' => 'mysql!mi14@',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'slave',
)),

'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=103.28.37.24;dbname=gamevina_v2',
  'username' => 'root',
  'password' => 'mysql!mi14@',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
