<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/08/05 05:00:23
sfConfig::add(array(
  'ex_meta_creator' => 'abc xyz',
  'ex_meta_title' => 'asdsa',
  'ex_meta_subject' => 'dsad',
  'ex_meta_description' => 'dsad',
  'ex_meta_keywords' => 'dsad',
  'ex_meta_category' => 'cdsa',
));
