<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/08/08 04:21:41
sfConfig::add(array(
  'mod_gvmanageruserregister_enabled' => true,
  'mod_gvmanageruserregister_view_class' => 'sfPHP',
));
