<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/08/05 05:00:30
sfConfig::add(array(
  'mod_tmctwitterbootstrap_enabled' => true,
  'mod_tmctwitterbootstrap_view_class' => 'sfPHP',
));
